language: python

python:
  - 2.6
  - 2.7
  - 3.5
  # - pypy

env:
  - TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=default
  - TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=select
  - TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=poll
  - TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=epoll
#  it's a pain to install gobject and pygtk in a virtualenv, so don't bother
#  - TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=gtk2

# only check all four reactors on 2.7
matrix:
  exclude:
    - python: 2.6
      env: TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=select
    - python: 2.6
      env: TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=poll
    - python: 2.6
      env: TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=epoll
    - python: 2.6
      env: TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=gtk2

    - python: 2.7
      env: TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=default
      # "file descriptor cannot be a negative integer" are back,
      # disable tests with select temporarily
    - python: 2.7
      env: TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=select

    - python: 3.5
      env: TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=select
    - python: 3.5
      env: TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=poll
      # the Travis builder complains about running trial --reactor=default
      # on Py3k, so disable it and use epoll explicitly
    - python: 3.5
      env: TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=default
    - python: 3.5
      env: TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=gtk2

    - python: pypy
      env: TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=select
    - python: pypy
      env: TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=poll
    - python: pypy
      env: TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=epoll
    - python: pypy
      env: TXPOSTGRES_TEST_HOST=127.0.0.1 TXPOSTGRES_TEST_USER=postgres REACTOR=gtk2


# only need psycopg2ct on PyPy, the rest gets normal psycopg2
# use zope.interface 3.8.0 since the latest version dropped Python 2.5 support
# use Twisted 15.3.0 on Python 2.6 since 15.4.0 dropped support
install:
  - sudo apt-get install libpq-dev
  - test "$TRAVIS_PYTHON_VERSION" == "pypy" && pip install psycopg2ct --use-mirrors || true
  - test "$TRAVIS_PYTHON_VERSION" != "pypy" && pip install psycopg2 --use-mirrors || true
  - pip install zope.interface==3.8.0 --use-mirrors
  - test "$TRAVIS_PYTHON_VERSION" == "2.6" && pip install twisted==15.3.0 --use-mirrors || true
  - test "$TRAVIS_PYTHON_VERSION" != "2.6" && pip install twisted --use-mirrors || true

before_script:
  - psql -U postgres -c 'create database twisted_test'

script: trial --reactor=$REACTOR test

notifications:
  email:
    - wulczer@wulczer.org
